### PR TITLE
Ft third task

### PR DESCRIPTION
**Pull request by amjedidiah**
# Implemented a working solution of the 3 tasks.

## Setup
1. Clone repo, run: `git clone https://github.com/amjedidiah/Frontend-Assessment.git tuteria`

2. Cd into repo, run: `cd tuteria`

3. Checkout into the latest updated branch, run: `git checkout ft-third-task`

4. Install dependencies, run: `yarn install` 
- **Yarn global install is required**
- [Click here](https://classic.yarnpkg.com/en/docs/install) to read up on how to install yarn globally 

5. Ensure nothing is running on the following ports of your computer: 
- PORT `3000`
- PORT `8080`

6. Start-up packages, run: `lerna run dev --parallel` 
-- **lerna global install is required**
-- Run `npm i -g lerna` to install lerna globally

7. Wait for packages to start completely:
- Wait till you see **any** of the following messages: 
`@tuteria/components:     75.4 kb: index.js.br` **OR** 
`@tuteria/www: event - compiled successfully` 

8. Visit `http://localhost:3000` in your browser

## Admin Login
1. key: `apple` hash: `AlphaEchoJalingo@1234`
1. key: `google` hash: `GalEchoJalingo@1234`

## BONUS POINTS
1. Frontend: NextJS

2. Backend: NextJS

3. DB used: `postgreSQL`
- DB is prepopulated on starting backend package

-  Also, connection string for PostgresSQL is read as an environmental variable in
i. The `data-layer` python project
ii. The `services/example/prisma` settings.

## Extra Notes
I added a step to task 1, in between Step 1 & Step 2 because running step 2 after Step 1 resulted in errors.
The added step prevented the error.

You can find this new Step in the README file as Step 2 in Task 1

### CODE REVIEW

**Comment by gbozee** [comment]
Thanks for attempting the assessment.

Unfortunately, the code was written in such a way that it is very difficult to replicate in an isolated environment and as a result I couldn't get the project running.

If a production url was provided with the hardcoding of connection strings for db as well as api, then I would have based my assessment on that. But since none was provided, I had to ensure I could get the code up and running locally which I couldn't.

image

You didn't provide the command to be run in order the server at port 8080.

Some of the major issues observed.
1. The lack of environmental variables for access to to the database. The DATABASE was hardcoded to the code  in this case.
2. No tests on the api endpoints were provided. That is the most reliable way to ensure that the implementation works.
3. The way NextJS api routes was used is fundamentally not in line with how it is described in the documentation. Also description of how to run this wasn't provided.
4. I observed certain dependencies like `components` and `packages`. If the instruction to run the project was followed to the letter, these would be completely unnecessary. 


The steps provided above to get the code working in an isolated environment fails. One can't assume the development environment used during development would be the same used in a staging or production settings. So code need to be written in such a way that based on the environment, it adapts accordingly.

I created a branch of the repo located at https://github.com/Tuteria/Frontend-Assessment/tree/amjedidiah-ft-third-task when trying to get the project running.

If you feel you can course correct and provide a solution that can be run in an isolated environment, then you are free to go ahead and attempt it again.

**Comment by amjedidiah** [comment]
Good evening @gbozee.
Thank you for your observations and feedback

## It Works On An Isolated machine 
- I indeed provided a command to run both the frontend and backend servers.
If you will kindly refer to my last comment under the *SETUP* section you will see that I provided 8 well explained steps to reproduce a working version of the assessment.
**You will need an internet connection to make sure this works**
- You got an error because **from the picture you shared, YOU DIDN'T USE ANY COMMAND from the 8 step method in the SETUP section in my last comment**
- I will however work on a production build, in the meantime, **please try running it again locally by referring to the 8 Step method in the SETUP section of my last comment**

### Environmental Variables
- I will provide environmental variables on my next commit

### Testing
- I tested my API endpoints with POSTMAN.
[Click here](https://documenter.getpostman.com/view/12127664/TVCiUmds) to see documentation to test it after getting the Backend server to run with **the 8 Step method I provided in the SETUP section of my last comment**
- I will implement tests in my code on my next commit

### NextJS endpoints
- I adhered strictly to the READme file for both the frontend and backend.
The Postman documentation proves this
When you get the assessment running using the 8 Step method in the SETUP section of my last comment, you can confirm this also 

## Final Notes
- I will implement the changes you requested in my subsequent commits
- *Please use the 8 Step Method in the SETUP section of my last comment**
- **Here are screenshots of a working implementation with the correct routes**
Screenshot (229)
Screenshot (245)
Screenshot (232)
Screenshot (234)
Screenshot (244)

**Comment by gbozee** [comment]
An isolated environment means all external dependencies e.g the database is confined in that environment. 

An example of an isolated environment is running the code in a docker container with all the dependencies specified in said container. The isolated container is responsible for providing its database not some external database connection. 

If for whatever reason the database url used goes down tomorrow, How easy would it be to replicate the same result?

As long as I am testing your implementation in a development environment, I am not interested in using your database. I can create mine myself. Hardcoding the database to be used doesn't make it isolated in any sense.

If you took a look at the branch I provided, https://github.com/Tuteria/Frontend-Assessment/tree/amjedidiah-ft-third-task

You would see I changed the following in `data-layer/settings.py`

```
DATABASE_URL = "postgres://smmuymuwdjdnwh:d32a41d2a517936b68388f2236d12e4680a3ea6e6bd42bfebc70aa3cde7e358e@ec2-52-71-85-210.compute-1.amazonaws.com:5432/dbekvrbcb0rauv"
```
to this
```
DATABASE_URL = os.getenv("DATABASE_URL","postgres://smmuymuwdjdnwh:d32a41d2a517936b68388f2236d12e4680a3ea6e6bd42bfebc70aa3cde7e358e@ec2-52-71-85-210.compute-1.amazonaws.com:5432/dbekvrbcb0rauv")
```

This is because this I can pass the DATABASE_URL I want to use. I don't have to be connected to the internet to use your database. That is what it means to have code reproducible in an isolated environment.

And like I mentioned earlier, the steps highlighted in the project wasn't followed. Prisma wasn't used in the implementation provided. There is a reason the the repository was provided with the steps to get up and running. This is different from just specifying the problem to be solved and leaving one to build their own repository structure. It is all about following convention.

Prisma wasn't used in the project for handling connection from the database, Knex was used which wasn't inline with the requirements. 

A datalayer python package was provided with steps on how to create the tables for the database but that wasn't the case done here. 

As much as initiative as a developer is supposed to be taken when solving a problem, you took initiative on the wrong problem. Instead of coming up with your way for running the project, time would have been better spent following the convention used in the project and on the actual problem like building the apis with prisma and running automated tests.

Evaluation is based on how well you followed the requirements which in this case wasn't done.

**Comment by amjedidiah** [comment]
Good afternoon Mr Biola

I understand what you mean now 
To be sincere, I thought the focus was on time and completing the project not necessarily sticking to the predefined conventions in the repo.
Therefore when it was taking time to come to terms with the conventions used, I resorted to technology I was conversant with.e.g: knex

If you will permit though, I could go ahead to reattempt the assessment, giving more attention to following the predefined convention rather than just completing the project.

Then do I still deploy the assessment in this current state? 
What say you?

Warm regards,
Amaraegbu Jedidiah

**Comment by gbozee** [comment]
That's fine. You can go ahead and reattempt it. I am not too fixated on how long it takes you. Of course there are chances that there are some technological choices chosen that you might not be familiar with and would have to learn.

**Comment by amjedidiah** [comment]
Alright @gbozee 
Currently involved in the Andela BuildforSDG & GADS 2020 programme
Both are very challenging

Will making a submission by next weekend be too late?

**Pull request closed without merging**
