### PR TITLE
Final Test Submission

### PR DESCRIPTION
**Pull request by limistah**
Complete code for the test
Most of the UIs are from [Segun98's Test Repo](https://github.com/Segun98/Frontend-Assessment)

Is the above called cheating? I don't think so, I think it is collaboration.

For the time and resources available, I don't think I can do any better, and I love standing on the shoulder of giants.

So, using his codes are just to tell him, I appreciate his wealth of skills and put him ahead.

Cheers!

### CODE REVIEW

**Comment by gbozee** [comment]
Great job attempting and completing the assessment.

## **Things done well**
1. The script file to create db records
2. Following the convention used in the codebase for handling dependencies as well as running commands.


## Some observations
1. No live link was provided. a `heroku.yml` file was created but no provision for a live link to the deployment in your PR message. If  a detailed description required to get the project running locally was provided., the live link won't have been necessary. Also the vercel link provided in the changeset doc points to a generic nextJS application and not the application.

2. The faker library, is it a dev dependency? Why was it added as an application dependency?

3. The code / UI copied was based on a false premise. Take a closer look at the requirements for Tasks 2, the first one is this
**POST /notes/create Anonymous note creation** note the anonymous there. This implies the endpoint can be called without any user required. Unfortunately, both the tests provided and the UI implementation failed to account for this. If a closer look at the comments I provided for the particular PR that was copied was taken, these issues would have been obvious and corrective measures would have been taken.

4. A description of the problems you attempted or links to the change-set files provided, would have been a better PR message than what was displayed. 

5. In the `services/app` package, the client host was hardcoded in the code. This becomes an issue when trying to deploy in a different environment.

6. Running the nextJS application, the `/notes/:note_id` route throws an error

7. The `/admin` route isn't protected. 

8. I suspect a misunderstanding based was made based on the fact that the `services/app` package is a NODEJS application. The bonus requirements specified a **NextJS** application. **NextJS** has an `api` section that handles api routes or alternatively provides a way to mount the nextJS frontend on top of an Express application. This was what was implied instead of a duplicate of the `example` service.


## **A few deliverables.**
 
1. Provide either a GettingStarted.MD or using the comment right here, a description of the steps you need to take to be able to get all the tests in `services/app` running. 
2. Refractor the yarn scripts and ensure you are using a .env file or a bash file housing the environmental variables instead of exposing them directly on the yarn scripts.

3. Replace all the client side api calls on the NextJS routes to server side calls. The data should be ready as the pages are displayed instead of after the page renders. (NextJS is a server side framework for a reason)

4. Update your version of the `ci.yml` in the github action workflow directory withe the one available at the [limistah-master](https://github.com/Tuteria/Frontend-Assessment/tree/limistah-master) branch. 

5. Provide solutions to the suggestions above.

if .env files are disabled in the .gitignore, you can disable them so that they get committed to version control. Alternatively, a simple startup bash scripts would also work in this case.


Do you think you can provide corrections to the above observations?

**Comment by limistah** [comment]
> Do you think you can provide corrections to the above observations?

Sure, I can.

**Comment by gbozee** [comment]
Hello? are you done with the task? 
Reason was because you didn't post any message here indicating you have?

**Comment by limistah** [comment]
Not yet,

I will post my final submission before the end of the day.

Thanks for checking out.

**Comment by gbozee** [comment]
Alright. looking forward to it.

**Pull request closed without merging**
