### PR TITLE
Initial Review

### PR DESCRIPTION
**Pull request by chidibede**
I am trying to deploy the app, encountering some problems but attempting to separate the backend and frontend and deploy in heroku and vercel respectively. Running it locally is described in the services/note README.md. I would love a feedback to improve on it.

### CODE REVIEW

**Comment by chidibede** [comment]
DATABASE_URL used is postgres://jqixbldb:C2B5Co2H5WmL_y620Qlt_n_QjdiovOqI@lallah.db.elephantsql.com:5432/jqixbldb

**Comment by gbozee** [comment]
Hello.

The implementation provided is not inline with the instructions provided. The steps required to create migrations for the project were clearly stated.

Please review accordingly.

**Comment by chidibede** [comment]
Thanks for pointing it out, I'm so sorry that I missed that part. I'm reviewing it and making the necessary corrections. I apologize for this oversight.

**Comment by chidibede** [comment]
Hello Mr. Biola, I have corrected the migration implementation in my code and went on to host the app. The client-side URL is https://deploy-next-note.vercel.app/ and the backend service URL is https://chidibede-tuteria-backend.herokuapp.com/ . Please I would love a second attempt at a review of my work, I am constantly trying to improve and your review will go a long way.
Yours Sincerely, Chidi

**Comment by gbozee** [comment]
Thanks for taking the time to complete the assessment. Really impressed with your implementation.

Though You failed to provide the admin credentials to test the admin route but its all good.

Please reach out to me at [Beee_sama](https://t.me/Beee_sama) on Telegram or send an email at biola@tuteria.com so that more information on the next stage of the interview can be provided.

**Pull request closed without merging**
