### PR TITLE
Front End Assessment Segun

### PR DESCRIPTION
**Pull request by Segun98**

### CODE REVIEW

**Comment by gbozee** [comment]
Hello. Just went through your implementation and observed a few things.

1. It appears your backend knowledge is severely limited so as a result, I would focus all the criticism on the purely the front end related task.

2. If you paid special attention to the dependencies already installed, you would have observed that nextjs was already a dependency in the project and also that all dependencies were installed in the root package.json. In your case, you added additional dependencies to the `www` subpackage.

3. You didn't interpret the problem correctly. The home page was supposed to consist of the list of notes not owned by anyone. Yet if one were to attempt landing on the home page to create a note, they are immediately redirected to the signup page. This shows you didn't have a clear understanding of the problem and also didn't bother to clarify if you were confused about what was supposed to be solved.

4. You didn't make use of environmental variables when working with api endpoint. Since one of the task was to get a production live link which you didn't, If you had done this. you would have seen that in a production environment, http://localhost:5000 would have thrown errors. It was only useful in a development setting.

5. Also, based on the way you exposed the api link to the frontend, you were bound to run into cors related issues when making calls to the api backend. You clearly didn't have a solution for this also.

6. You failed to provide steps of the actions you carried out. Attempting to get the implementation running resulted in inaction when trying to signup a user. It would have been better if you had provided a link of a working version. But since I tried setting it up and it didn't work, that is what I can judge you with instead.

7. You didn't make any attempt on the bonus tasks.

Do you feel the project was too difficult for the role at hand? or the time was too short for you to get all the implementation working?

**Comment by Segun98** [comment]
2. Due to my limited experience, I was not familiar with having a root package.json that contains all dependencies across a project, I usually separate concerns in my personal projects. 

I also ran into a small problem in the back end that was fixed by installing a package in that directory. 

3. I ensured sign up to a user who isn't logged in in order to map users to their notes by attaching a user id to each note.

5. I installed the cors package on the back-end and set it up in "index.ts" so I did not run into cors problems on my side.


The project was not too difficult, the ReadMe was detailed and I understood the tasks. 

I must admit I was not familiar with some of the tools I was expected to use, especially for the bonus points. 

I had issues with electricity so I didn't start the project until 24th, Monday, so I couldn't learn all in that period.

**Comment by gbozee** [comment]
2. That is exactly why I ensured all the information you needed about the tools responsible for setting up the project was mentioned in the READMe (Lerna). Part of the test is the ability to be able to figure stuff out on your own that is different from what you are used too.

3. I do not understand what you meant by `I ensured sign up to a user who isn't logged in in order to map users to their notes by attaching a user id to each note.` The requirement clearly stated anonymous users should be able to create notes but that wasn't what you did. and you didn't provide any explanation of what you did differently.

If you had more time to work on this, are you confident you would have performed a better job than what you did now?

**Comment by Segun98** [comment]
3. Since the task requires a user page which displays the list of notes for the user whose username is passed in the route, and 
a page `/admin`  that displays the number of notes created by a user, I thought I should ensure sign up so I would know who created which note.  

Yes, I am confident I would do better than what I have done. Thank you.

**Comment by gbozee** [comment]
You could try attempting the project again providing corrections to issues raised. When you are done submit a different PR of your implementation.

**Pull request closed without merging**
