### PR TITLE
Task 3 submission

### PR DESCRIPTION
**Pull request by proxiex**

### CODE REVIEW

**Comment by gbozee** [comment]
The attempt at the assessment is greatly appreciated.

Unfortunately, the submission appears incomplete as I was unable to replicate your environment locally. This is mostly because of the failure to provide steps required to get your code up and running.

On the attempt I made, here is the error that occurred when visiting the home page

image

Making a call to the api endpoint at `http://localhost:3000/api/notes` returned the following error.

image

**Bear in mind this was after the environmental variable for the DATABASE_URL was set as well as running `yarn db:generate`**.

Other issues found with the submission are as follows
1. Failure to provide the corresponding tests for Task 2. There is no way to guaranty that the implementation provided does what it says it does without automated tests to verify them.

This assessment isn't just testing technical skills but also ability to communicate effectively when when working on a project. One needs to ensure that any responsibility or task they embark upon, doesn't cause trouble or stress for other members of the team.

It would be great if the suggestions provided above is reviewed and the appropriate changes are made.

**Comment by proxiex** [comment]
Thank you for the feedback,  I will make the adjustment to the things you have mentioned.

**Comment by proxiex** [comment]
I have implemented the feedback. ✨
- Setup instructions are located in `services/notes-app` directory

**Comment by gbozee** [comment]
I am impressed with the changes you made. Below are some of the things done really well

1. The UI implementation of the web application. Nice usage of Chakra-UI
2. Addition of the test endpoints and ensuring that they all pass in an isolated environment https://github.com/Tuteria/Frontend-Assessment/runs/1095492729?check_suite_focus=true
3. Sticking to most of the convention used in the project. 

A few things not considered were.
1. the `/admin` route wasn't created. Also no superuser login was provided so that the list of users with notes could be viewable from the admin.
2. The route generated when an anonymous note is created is kinda off. Would have been better to be redirected to the home page instead of the `/users/<username>/notes ` page
3. The inability to view notes belonging to a specific user.

All in all, This was an impressive assessment solution. Please reach out to me either at biola@tuteria.com or at [Beee_sama](https://t.me/Beee_sama) on Telegram.

**Pull request closed without merging**
